name: yod
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  yod_network_http:
    path: packages/yod_network_http
  yod_data:
    path: packages/yod_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^6.3.3

flutter:
